# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DroneDashboard(object):
    def setupUi(self, DroneDashboard):
        DroneDashboard.setObjectName("DroneDashboard")
        DroneDashboard.resize(1899, 1272)
        DroneDashboard.setAutoFillBackground(False)
        DroneDashboard.setStyleSheet("QMainWindow{\n"
"    background-color: black;\n"
"}")
        DroneDashboard.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(DroneDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPort.setGeometry(QtCore.QRect(50, 210, 101, 41))
        self.comboBoxPort.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: green;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 10, 571, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label.setObjectName("label")
        self.labelCameraFeed = QtWidgets.QLabel(self.centralwidget)
        self.labelCameraFeed.setGeometry(QtCore.QRect(430, 120, 1101, 561))
        self.labelCameraFeed.setText("")
        self.labelCameraFeed.setScaledContents(True)
        self.labelCameraFeed.setObjectName("labelCameraFeed")
        self.CaptureButton = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureButton.setGeometry(QtCore.QRect(880, 780, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CaptureButton.setFont(font)
        self.CaptureButton.setStyleSheet("QPushButton {\n"
"    background-color: #2023C5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"")
        self.CaptureButton.setObjectName("CaptureButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 480, 331, 631))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: cyan;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(180, 40, 71, 31))
        self.lcdNumber.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(180, 130, 71, 31))
        self.lcdNumber_2.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(180, 90, 71, 31))
        self.lcdNumber_3.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(180, 180, 71, 31))
        self.lcdNumber_4.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_5.setGeometry(QtCore.QRect(180, 230, 71, 31))
        self.lcdNumber_5.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_6.setGeometry(QtCore.QRect(180, 280, 71, 31))
        self.lcdNumber_6.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_7.setGeometry(QtCore.QRect(180, 330, 71, 31))
        self.lcdNumber_7.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_8.setGeometry(QtCore.QRect(180, 380, 71, 31))
        self.lcdNumber_8.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_9.setGeometry(QtCore.QRect(180, 430, 71, 31))
        self.lcdNumber_9.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_10.setGeometry(QtCore.QRect(180, 480, 71, 31))
        self.lcdNumber_10.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_11.setGeometry(QtCore.QRect(180, 530, 71, 31))
        self.lcdNumber_11.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_12.setGeometry(QtCore.QRect(180, 580, 71, 31))
        self.lcdNumber_12.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: cyan;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.Latitude = QtWidgets.QLabel(self.groupBox)
        self.Latitude.setGeometry(QtCore.QRect(10, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Latitude.setFont(font)
        self.Latitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Latitude.setObjectName("Latitude")
        self.Longitude = QtWidgets.QLabel(self.groupBox)
        self.Longitude.setGeometry(QtCore.QRect(10, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Longitude.setFont(font)
        self.Longitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Longitude.setObjectName("Longitude")
        self.Altitude = QtWidgets.QLabel(self.groupBox)
        self.Altitude.setGeometry(QtCore.QRect(10, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Altitude.setFont(font)
        self.Altitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Altitude.setObjectName("Altitude")
        self.Roll = QtWidgets.QLabel(self.groupBox)
        self.Roll.setGeometry(QtCore.QRect(10, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Roll.setFont(font)
        self.Roll.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Roll.setObjectName("Roll")
        self.Pitch = QtWidgets.QLabel(self.groupBox)
        self.Pitch.setGeometry(QtCore.QRect(10, 240, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pitch.setFont(font)
        self.Pitch.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Pitch.setObjectName("Pitch")
        self.Heading = QtWidgets.QLabel(self.groupBox)
        self.Heading.setGeometry(QtCore.QRect(10, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Heading.setObjectName("Heading")
        self.Satellites = QtWidgets.QLabel(self.groupBox)
        self.Satellites.setGeometry(QtCore.QRect(10, 330, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Satellites.setFont(font)
        self.Satellites.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Satellites.setObjectName("Satellites")
        self.Temperature = QtWidgets.QLabel(self.groupBox)
        self.Temperature.setGeometry(QtCore.QRect(10, 390, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Temperature.setFont(font)
        self.Temperature.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Temperature.setScaledContents(False)
        self.Temperature.setObjectName("Temperature")
        self.Distance1 = QtWidgets.QLabel(self.groupBox)
        self.Distance1.setGeometry(QtCore.QRect(10, 440, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Distance1.setFont(font)
        self.Distance1.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Distance1.setObjectName("Distance1")
        self.Distance2 = QtWidgets.QLabel(self.groupBox)
        self.Distance2.setGeometry(QtCore.QRect(10, 490, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Distance2.setFont(font)
        self.Distance2.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Distance2.setObjectName("Distance2")
        self.Distance3 = QtWidgets.QLabel(self.groupBox)
        self.Distance3.setGeometry(QtCore.QRect(10, 540, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Distance3.setFont(font)
        self.Distance3.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Distance3.setObjectName("Distance3")
        self.Distance4 = QtWidgets.QLabel(self.groupBox)
        self.Distance4.setGeometry(QtCore.QRect(10, 580, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Distance4.setFont(font)
        self.Distance4.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Distance4.setObjectName("Distance4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1720, 630, 47, 14))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../OneDrive/Desktop/.designer/backup/.venv/images/battery.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1730, 780, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1730, 910, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1730, 1020, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect.setGeometry(QtCore.QRect(160, 210, 151, 41))
        self.Disconnect.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: green;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Disconnect.setIcon(icon)
        self.Disconnect.setObjectName("Disconnect")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1730, 670, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.ErrorButton = QtWidgets.QPushButton(self.centralwidget)
        self.ErrorButton.setGeometry(QtCore.QRect(1590, 760, 91, 81))
        self.ErrorButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ErrorButton.setIcon(icon1)
        self.ErrorButton.setObjectName("ErrorButton")
        self.ArmedUnarmedButton = QtWidgets.QPushButton(self.centralwidget)
        self.ArmedUnarmedButton.setGeometry(QtCore.QRect(1590, 880, 91, 81))
        self.ArmedUnarmedButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/drone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ArmedUnarmedButton.setIcon(icon2)
        self.ArmedUnarmedButton.setObjectName("ArmedUnarmedButton")
        self.BatteryVoltage = QtWidgets.QPushButton(self.centralwidget)
        self.BatteryVoltage.setGeometry(QtCore.QRect(1590, 1000, 91, 81))
        self.BatteryVoltage.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BatteryVoltage.setIcon(icon3)
        self.BatteryVoltage.setObjectName("BatteryVoltage")
        self.GPSButton = QtWidgets.QPushButton(self.centralwidget)
        self.GPSButton.setGeometry(QtCore.QRect(1590, 640, 91, 81))
        self.GPSButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/google-maps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GPSButton.setIcon(icon4)
        self.GPSButton.setObjectName("GPSButton")
        self.LabelTimer = QtWidgets.QLabel(self.centralwidget)
        self.LabelTimer.setGeometry(QtCore.QRect(1730, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTimer.setFont(font)
        self.LabelTimer.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelTimer.setObjectName("LabelTimer")
        self.TimerButton = QtWidgets.QPushButton(self.centralwidget)
        self.TimerButton.setGeometry(QtCore.QRect(1590, 120, 91, 71))
        self.TimerButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/flight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimerButton.setIcon(icon5)
        self.TimerButton.setObjectName("TimerButton")
        self.LabelMode = QtWidgets.QLabel(self.centralwidget)
        self.LabelMode.setGeometry(QtCore.QRect(800, 890, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelMode.setFont(font)
        self.LabelMode.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelMode.setObjectName("LabelMode")
        self.LabelModeType = QtWidgets.QLabel(self.centralwidget)
        self.LabelModeType.setGeometry(QtCore.QRect(1020, 890, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LabelModeType.setFont(font)
        self.LabelModeType.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelModeType.setObjectName("LabelModeType")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(800, 960, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1020, 970, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.CloseButton = QtWidgets.QToolButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(1830, 10, 71, 51))
        self.CloseButton.setIcon(icon)
        self.CloseButton.setObjectName("CloseButton")
        self.logolabel = QtWidgets.QLabel(self.centralwidget)
        self.logolabel.setGeometry(QtCore.QRect(50, 70, 251, 101))
        self.logolabel.setStyleSheet("QLabel#logoLabel {\n"
"    qproperty-pixmap: url(:/Users/pavit/OneDrive/Desktop/Learning/python/drone/images/logo.png); \n"
"}")
        self.logolabel.setText("")
        self.logolabel.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.logolabel.setObjectName("logolabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 370, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:cyan;\n"
"}")
        self.label_2.setObjectName("label_2")
        DroneDashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DroneDashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1899, 22))
        self.menubar.setObjectName("menubar")
        DroneDashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DroneDashboard)
        self.statusbar.setObjectName("statusbar")
        DroneDashboard.setStatusBar(self.statusbar)

        self.retranslateUi(DroneDashboard)
        QtCore.QMetaObject.connectSlotsByName(DroneDashboard)

    def retranslateUi(self, DroneDashboard):
        _translate = QtCore.QCoreApplication.translate
        DroneDashboard.setWindowTitle(_translate("DroneDashboard", "MainWindow"))
        self.label.setText(_translate("DroneDashboard", "                      Flight Monitor"))
        self.CaptureButton.setText(_translate("DroneDashboard", "Capture"))
        self.Latitude.setText(_translate("DroneDashboard", "Latitude"))
        self.Longitude.setText(_translate("DroneDashboard", "Longitude"))
        self.Altitude.setText(_translate("DroneDashboard", "Altitude"))
        self.Roll.setText(_translate("DroneDashboard", "Roll"))
        self.Pitch.setText(_translate("DroneDashboard", "Pitch"))
        self.Heading.setText(_translate("DroneDashboard", "Heading"))
        self.Satellites.setText(_translate("DroneDashboard", "Satellites"))
        self.Temperature.setText(_translate("DroneDashboard", "Temperature"))
        self.Distance1.setText(_translate("DroneDashboard", "Dist RH US"))
        self.Distance2.setText(_translate("DroneDashboard", "Dist LH US"))
        self.Distance3.setText(_translate("DroneDashboard", "Dist Front US"))
        self.Distance4.setText(_translate("DroneDashboard", "Dist Upper US"))
        self.label_15.setText(_translate("DroneDashboard", "TextLabel"))
        self.label_16.setText(_translate("DroneDashboard", "TextLabel"))
        self.label_18.setText(_translate("DroneDashboard", "TextLabel"))
        self.Disconnect.setText(_translate("DroneDashboard", "Disconnect"))
        self.label_19.setText(_translate("DroneDashboard", "TextLabel"))
        self.ErrorButton.setText(_translate("DroneDashboard", "Error"))
        self.LabelTimer.setText(_translate("DroneDashboard", "00:00:00"))
        self.LabelMode.setText(_translate("DroneDashboard", "Main Mode"))
        self.LabelModeType.setText(_translate("DroneDashboard", "TextLabel"))
        self.label_20.setText(_translate("DroneDashboard", "Sub Mode"))
        self.label_21.setText(_translate("DroneDashboard", "TextLabel"))
        self.CloseButton.setText(_translate("DroneDashboard", "..."))
        self.label_2.setText(_translate("DroneDashboard", "TELEMETRY DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DroneDashboard = QtWidgets.QMainWindow()
    ui = Ui_DroneDashboard()
    ui.setupUi(DroneDashboard)
    DroneDashboard.show()
    sys.exit(app.exec_())
