# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DroneDashboard(object):
    def setupUi(self, DroneDashboard):
        DroneDashboard.setObjectName("DroneDashboard")
        DroneDashboard.resize(1899, 1272)
        DroneDashboard.setAutoFillBackground(False)
        DroneDashboard.setStyleSheet("QMainWindow{\n"
"    background-color: black;\n"
"}")
        DroneDashboard.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(DroneDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPort.setGeometry(QtCore.QRect(50, 250, 161, 51))
        self.comboBoxPort.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: green;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.comboBoxPort.setCurrentText("")
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 10, 571, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.label.setObjectName("label")
        self.labelCameraFeed = QtWidgets.QLabel(self.centralwidget)
        self.labelCameraFeed.setGeometry(QtCore.QRect(430, 120, 1101, 561))
        self.labelCameraFeed.setText("")
        self.labelCameraFeed.setScaledContents(True)
        self.labelCameraFeed.setObjectName("labelCameraFeed")
        self.CaptureButton = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureButton.setGeometry(QtCore.QRect(880, 780, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CaptureButton.setFont(font)
        self.CaptureButton.setStyleSheet("QPushButton {\n"
"    background-color: #2023C5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"")
        self.CaptureButton.setObjectName("CaptureButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 470, 311, 551))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: cyan;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(200, 40, 71, 31))
        self.lcdNumber.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(200, 130, 71, 31))
        self.lcdNumber_2.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(200, 80, 71, 31))
        self.lcdNumber_3.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(200, 180, 71, 31))
        self.lcdNumber_4.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_5.setGeometry(QtCore.QRect(200, 230, 71, 31))
        self.lcdNumber_5.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_6.setGeometry(QtCore.QRect(200, 280, 71, 31))
        self.lcdNumber_6.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_7.setGeometry(QtCore.QRect(200, 330, 71, 31))
        self.lcdNumber_7.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_9.setGeometry(QtCore.QRect(200, 380, 71, 31))
        self.lcdNumber_9.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_10.setGeometry(QtCore.QRect(200, 430, 71, 31))
        self.lcdNumber_10.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_12.setGeometry(QtCore.QRect(200, 480, 71, 31))
        self.lcdNumber_12.setStyleSheet("QLCDNumber {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.Latitude = QtWidgets.QLabel(self.groupBox)
        self.Latitude.setGeometry(QtCore.QRect(30, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Latitude.setFont(font)
        self.Latitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Latitude.setObjectName("Latitude")
        self.Longitude = QtWidgets.QLabel(self.groupBox)
        self.Longitude.setGeometry(QtCore.QRect(30, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Longitude.setFont(font)
        self.Longitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Longitude.setObjectName("Longitude")
        self.Altitude = QtWidgets.QLabel(self.groupBox)
        self.Altitude.setGeometry(QtCore.QRect(30, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Altitude.setFont(font)
        self.Altitude.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Altitude.setObjectName("Altitude")
        self.Roll = QtWidgets.QLabel(self.groupBox)
        self.Roll.setGeometry(QtCore.QRect(30, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Roll.setFont(font)
        self.Roll.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Roll.setObjectName("Roll")
        self.Pitch = QtWidgets.QLabel(self.groupBox)
        self.Pitch.setGeometry(QtCore.QRect(30, 240, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pitch.setFont(font)
        self.Pitch.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Pitch.setObjectName("Pitch")
        self.Heading = QtWidgets.QLabel(self.groupBox)
        self.Heading.setGeometry(QtCore.QRect(30, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Heading.setObjectName("Heading")
        self.Satellites = QtWidgets.QLabel(self.groupBox)
        self.Satellites.setGeometry(QtCore.QRect(30, 330, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Satellites.setFont(font)
        self.Satellites.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.Satellites.setObjectName("Satellites")
        self.DistanceRH = QtWidgets.QLabel(self.groupBox)
        self.DistanceRH.setGeometry(QtCore.QRect(30, 390, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DistanceRH.setFont(font)
        self.DistanceRH.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.DistanceRH.setObjectName("DistanceRH")
        self.DistanceLH = QtWidgets.QLabel(self.groupBox)
        self.DistanceLH.setGeometry(QtCore.QRect(30, 440, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DistanceLH.setFont(font)
        self.DistanceLH.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.DistanceLH.setObjectName("DistanceLH")
        self.DistanceUpper = QtWidgets.QLabel(self.groupBox)
        self.DistanceUpper.setGeometry(QtCore.QRect(30, 470, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DistanceUpper.setFont(font)
        self.DistanceUpper.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.DistanceUpper.setObjectName("DistanceUpper")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1720, 560, 47, 14))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../OneDrive/Desktop/.designer/backup/.venv/images/battery.png"))
        self.label_14.setObjectName("label_14")
        self.error_status = QtWidgets.QLabel(self.centralwidget)
        self.error_status.setGeometry(QtCore.QRect(1730, 710, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_status.setFont(font)
        self.error_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.error_status.setText("")
        self.error_status.setObjectName("error_status")
        self.armed_status = QtWidgets.QLabel(self.centralwidget)
        self.armed_status.setGeometry(QtCore.QRect(1730, 840, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.armed_status.setFont(font)
        self.armed_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.armed_status.setText("")
        self.armed_status.setObjectName("armed_status")
        self.battery_status = QtWidgets.QLabel(self.centralwidget)
        self.battery_status.setGeometry(QtCore.QRect(1730, 950, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.battery_status.setFont(font)
        self.battery_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.battery_status.setText("")
        self.battery_status.setObjectName("battery_status")
        self.gps_status = QtWidgets.QLabel(self.centralwidget)
        self.gps_status.setGeometry(QtCore.QRect(1730, 600, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gps_status.setFont(font)
        self.gps_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.gps_status.setText("")
        self.gps_status.setObjectName("gps_status")
        self.ErrorButton = QtWidgets.QPushButton(self.centralwidget)
        self.ErrorButton.setGeometry(QtCore.QRect(1590, 690, 91, 81))
        self.ErrorButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ErrorButton.setIcon(icon)
        self.ErrorButton.setObjectName("ErrorButton")
        self.ArmedUnarmedButton = QtWidgets.QPushButton(self.centralwidget)
        self.ArmedUnarmedButton.setGeometry(QtCore.QRect(1590, 810, 91, 81))
        self.ArmedUnarmedButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/drone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ArmedUnarmedButton.setIcon(icon1)
        self.ArmedUnarmedButton.setObjectName("ArmedUnarmedButton")
        self.BatteryVoltage = QtWidgets.QPushButton(self.centralwidget)
        self.BatteryVoltage.setGeometry(QtCore.QRect(1590, 930, 91, 81))
        self.BatteryVoltage.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BatteryVoltage.setIcon(icon2)
        self.BatteryVoltage.setObjectName("BatteryVoltage")
        self.GPSButton = QtWidgets.QPushButton(self.centralwidget)
        self.GPSButton.setGeometry(QtCore.QRect(1590, 570, 91, 81))
        self.GPSButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/google-maps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GPSButton.setIcon(icon3)
        self.GPSButton.setObjectName("GPSButton")
        self.LabelTimer = QtWidgets.QLabel(self.centralwidget)
        self.LabelTimer.setGeometry(QtCore.QRect(1730, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTimer.setFont(font)
        self.LabelTimer.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelTimer.setObjectName("LabelTimer")
        self.TimerButton = QtWidgets.QPushButton(self.centralwidget)
        self.TimerButton.setGeometry(QtCore.QRect(1590, 120, 91, 71))
        self.TimerButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/flight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TimerButton.setIcon(icon4)
        self.TimerButton.setObjectName("TimerButton")
        self.LabelMode = QtWidgets.QLabel(self.centralwidget)
        self.LabelMode.setGeometry(QtCore.QRect(800, 890, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelMode.setFont(font)
        self.LabelMode.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelMode.setObjectName("LabelMode")
        self.mainmode_status = QtWidgets.QLabel(self.centralwidget)
        self.mainmode_status.setGeometry(QtCore.QRect(1020, 890, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mainmode_status.setFont(font)
        self.mainmode_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.mainmode_status.setText("")
        self.mainmode_status.setObjectName("mainmode_status")
        self.LabelSubMode = QtWidgets.QLabel(self.centralwidget)
        self.LabelSubMode.setGeometry(QtCore.QRect(800, 960, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelSubMode.setFont(font)
        self.LabelSubMode.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.LabelSubMode.setObjectName("LabelSubMode")
        self.submode_status = QtWidgets.QLabel(self.centralwidget)
        self.submode_status.setGeometry(QtCore.QRect(1020, 970, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submode_status.setFont(font)
        self.submode_status.setStyleSheet("QLabel {\n"
"    color: cyan;\n"
"}")
        self.submode_status.setText("")
        self.submode_status.setObjectName("submode_status")
        self.CloseButton = QtWidgets.QToolButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(1830, 10, 71, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon5)
        self.CloseButton.setObjectName("CloseButton")
        self.logolabel = QtWidgets.QLabel(self.centralwidget)
        self.logolabel.setGeometry(QtCore.QRect(50, 70, 251, 101))
        self.logolabel.setStyleSheet("QLabel#logoLabel {\n"
"    qproperty-pixmap: url(:/Users/pavit/OneDrive/Desktop/Learning/python/drone/images/logo.png); \n"
"}")
        self.logolabel.setText("")
        self.logolabel.setPixmap(QtGui.QPixmap("images/logo.png"))
        self.logolabel.setObjectName("logolabel")
        self.telemetry_data = QtWidgets.QLabel(self.centralwidget)
        self.telemetry_data.setGeometry(QtCore.QRect(50, 370, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.telemetry_data.setFont(font)
        self.telemetry_data.setStyleSheet("QLabel{\n"
"color:cyan;\n"
"}")
        self.telemetry_data.setObjectName("telemetry_data")
        self.SelectPortText = QtWidgets.QLabel(self.centralwidget)
        self.SelectPortText.setGeometry(QtCore.QRect(50, 200, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SelectPortText.setFont(font)
        self.SelectPortText.setStyleSheet("QLabel{\n"
"color: green;\n"
"}")
        self.SelectPortText.setObjectName("SelectPortText")
        DroneDashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DroneDashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1899, 22))
        self.menubar.setObjectName("menubar")
        DroneDashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DroneDashboard)
        self.statusbar.setObjectName("statusbar")
        DroneDashboard.setStatusBar(self.statusbar)

        self.retranslateUi(DroneDashboard)
        QtCore.QMetaObject.connectSlotsByName(DroneDashboard)

    def retranslateUi(self, DroneDashboard):
        _translate = QtCore.QCoreApplication.translate
        DroneDashboard.setWindowTitle(_translate("DroneDashboard", "MainWindow"))
        self.comboBoxPort.setAccessibleName(_translate("DroneDashboard", "Select Port"))
        self.comboBoxPort.setPlaceholderText(_translate("DroneDashboard", "SELECT PORT"))
        self.label.setText(_translate("DroneDashboard", "                      Flight Monitor"))
        self.CaptureButton.setText(_translate("DroneDashboard", "Capture"))
        self.Latitude.setText(_translate("DroneDashboard", "Latitude"))
        self.Longitude.setText(_translate("DroneDashboard", "Longitude"))
        self.Altitude.setText(_translate("DroneDashboard", "Altitude"))
        self.Roll.setText(_translate("DroneDashboard", "Roll"))
        self.Pitch.setText(_translate("DroneDashboard", "Pitch"))
        self.Heading.setText(_translate("DroneDashboard", "Heading"))
        self.Satellites.setText(_translate("DroneDashboard", "Satellites"))
        self.DistanceRH.setText(_translate("DroneDashboard", "Dist RH US"))
        self.DistanceLH.setText(_translate("DroneDashboard", "Dist LH US"))
        self.DistanceUpper.setText(_translate("DroneDashboard", "Dist Upper US"))
        self.ErrorButton.setText(_translate("DroneDashboard", "Error"))
        self.LabelTimer.setText(_translate("DroneDashboard", "00:00:00"))
        self.LabelMode.setText(_translate("DroneDashboard", "Main Mode"))
        self.LabelSubMode.setText(_translate("DroneDashboard", "Sub Mode"))
        self.CloseButton.setText(_translate("DroneDashboard", "..."))
        self.telemetry_data.setText(_translate("DroneDashboard", "TELEMETRY DATA"))
        self.SelectPortText.setText(_translate("DroneDashboard", "Select Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DroneDashboard = QtWidgets.QMainWindow()
    ui = Ui_DroneDashboard()
    ui.setupUi(DroneDashboard)
    DroneDashboard.show()
    sys.exit(app.exec_())
